# Generated by Django 6.0.3 on 2026-07-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_currency',
            field=models.CharField(blank=True, choices=[('us_dollar', 'US Dollar'), ('pound', 'Pound'), ('taka', 'Bangladeshi Taka')], max_length=20, null=True, verbose_name='Account Currency'),
        ),
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(blank=True, choices=[('current', 'Current'), ('savings', 'Savings')], max_length=20, null=True, verbose_name='Account Type'),
        ),
    ]
